# Rename image files to match products.json naming conventions
mv assets/7days_cookies_and_cream.png assets/7days_croissant_cream_and_cookies_flavor_1pcs.png
mv assets/7days_vanilla_and_chocolate.webp assets/7days_croissant_cocoa_and_vanilla_flavor_1pcs.webp
mv assets/DORITOS_FLAMING_HOT.png assets/chips_doritos_flaming_hot_75g.png
mv assets/LAYS_CHEESE.webp assets/chips_lays_cheese_flavor_200g.webp
mv assets/LAYS_FROMAGE.png assets/chips_lays_fromage_flavor_200g.png
mv assets/LAYS_ONION.png assets/chips_lays_onion_flavor_200g.png
mv assets/LAYS_TOMATO.png assets/chips_lays_tomato_flavor_200g.png
mv assets/PRINGLES_ORIGINAL.png assets/chips_pringles_original_185g.png
mv assets/PRINGLES_SOUR_CREAM_AND_ONION.png assets/chips_pringles_sour_cream_and_onion_185g.png
mv assets/pepsi_0.33.png assets/pepsi_can_0.33l.png
mv assets/pepsi_0.5L.jpeg assets/pepsi_bottle_0.5l.jpeg
mv assets/pepsi_1.5L.png assets/pepsi_bottle_1.5l.png
mv assets/mirinda_0.33.png assets/mirinda_can_0.33l.png
mv assets/mirinda_0.5L.png assets/mirinda_bottle_0.5l.png
mv assets/redbull_0.25.png assets/red_bull_original_0.25l.png
mv assets/cult_juice_ocean.png assets/cult_juicy_ocean_flavor_0.5l.png
mv assets/cult_original.png assets/cult_original_flavor_0.5l.png
mv assets/juice_0.2L.png assets/juice_multifruit_pack_with_straw_0.2l.png
mv assets/haribo.webp assets/jelly_haribo_goldbears_100g.webp
mv assets/jelly_cola.png assets/jelly_sweet_corner_cola_flavor_300g.png
mv assets/jelly_happy_bears.png assets/jelly_sweet_corner_happy_bears_300g.png
mv assets/roger_nut.png assets/roger_chocolate_waffles_nut_flavor_40g.png
mv assets/roger_coconut.png assets/roger_chocolate_waffles_coconut_flavor_40g.png
mv assets/roger_milk.png assets/roger_chocolate_waffles_milk_chocolate_flavor_40g.png
mv assets/kitkat.png assets/kitkat_chocolate_40g.png
mv assets/milka-oreo.webp assets/milka_oreo_chocolate_bar_100g.webp
mv assets/glazed_curd_vanilla.png assets/glazed_curds_vanilla_flavor_1pcs.png
mv assets/zalgirio.png assets/sandwich_zalgirio_chicken_kebab_cucumber_and_cheese_255g.png
